# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate wayland-protocols

Name:           rust-wayland-protocols
Version:        0.30.1
Release:        %autorelease
Summary:        Generated API for the officials wayland protocol extensions

License:        MIT
URL:            https://crates.io/crates/wayland-protocols
Source:         %{crates_source}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Generated API for the officials wayland protocol extensions.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE.txt
%license %{crate_instdir}/protocols/COPYING
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+client-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+client-devel %{_description}

This package contains library source intended for building other packages which
use the "client" feature of the "%{crate}" crate.

%files       -n %{name}+client-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+server-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+server-devel %{_description}

This package contains library source intended for building other packages which
use the "server" feature of the "%{crate}" crate.

%files       -n %{name}+server-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+staging-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+staging-devel %{_description}

This package contains library source intended for building other packages which
use the "staging" feature of the "%{crate}" crate.

%files       -n %{name}+staging-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unstable-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unstable-devel %{_description}

This package contains library source intended for building other packages which
use the "unstable" feature of the "%{crate}" crate.

%files       -n %{name}+unstable-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wayland-client-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wayland-client-devel %{_description}

This package contains library source intended for building other packages which
use the "wayland-client" feature of the "%{crate}" crate.

%files       -n %{name}+wayland-client-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wayland-server-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wayland-server-devel %{_description}

This package contains library source intended for building other packages which
use the "wayland-server" feature of the "%{crate}" crate.

%files       -n %{name}+wayland-server-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -a

%build
%cargo_build -a

%install
%cargo_install -a

%changelog
%autochangelog
