# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate quick-xml

Name:           rust-quick-xml
Version:        0.28.0
Release:        %autorelease
Summary:        High performance xml reader and writer

License:        MIT
URL:            https://crates.io/crates/quick-xml
Source:         %{crates_source}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
High performance xml reader and writer.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-MIT.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+arbitrary-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+arbitrary-devel %{_description}

This package contains library source intended for building other packages which
use the "arbitrary" feature of the "%{crate}" crate.

%files       -n %{name}+arbitrary-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async-tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-tokio-devel %{_description}

This package contains library source intended for building other packages which
use the "async-tokio" feature of the "%{crate}" crate.

%files       -n %{name}+async-tokio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+document-features-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+document-features-devel %{_description}

This package contains library source intended for building other packages which
use the "document-features" feature of the "%{crate}" crate.

%files       -n %{name}+document-features-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+encoding-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+encoding-devel %{_description}

This package contains library source intended for building other packages which
use the "encoding" feature of the "%{crate}" crate.

%files       -n %{name}+encoding-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+encoding_rs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+encoding_rs-devel %{_description}

This package contains library source intended for building other packages which
use the "encoding_rs" feature of the "%{crate}" crate.

%files       -n %{name}+encoding_rs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+escape-html-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+escape-html-devel %{_description}

This package contains library source intended for building other packages which
use the "escape-html" feature of the "%{crate}" crate.

%files       -n %{name}+escape-html-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+overlapped-lists-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+overlapped-lists-devel %{_description}

This package contains library source intended for building other packages which
use the "overlapped-lists" feature of the "%{crate}" crate.

%files       -n %{name}+overlapped-lists-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-types-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-types-devel %{_description}

This package contains library source intended for building other packages which
use the "serde-types" feature of the "%{crate}" crate.

%files       -n %{name}+serde-types-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serialize-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serialize-devel %{_description}

This package contains library source intended for building other packages which
use the "serialize" feature of the "%{crate}" crate.

%files       -n %{name}+serialize-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
