# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate wayland-scanner

Name:           rust-wayland-scanner
Version:        0.30.1
Release:        %autorelease
Summary:        Wayland Scanner for generating rust APIs from XML wayland protocol files

License:        MIT
URL:            https://crates.io/crates/wayland-scanner
Source:         %{crates_source}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Wayland Scanner for generating rust APIs from XML wayland protocol
files.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE.txt
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
